[package]
name = "sponge"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dioxus = { version = "0.5", features = ["web"] }
nalgebra = "0.31.0"
async-timer = "1.0.0-beta.8"
